# Generated by Django 4.1.1 on 2022-09-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregistration',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
